"""baseline schema

Revision ID: 1549f3f1dbf8
Revises: 
Create Date: 2026-08-18 19:18:01.466534
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1549f3f1dbf8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('owner_team', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('risk_tier', sa.String(length=24), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.Column('declared_models', sa.JSON(), nullable=False),
    sa.Column('declared_tools', sa.JSON(), nullable=False),
    sa.Column('data_classes', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_slug'), ['slug'], unique=True)

    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=True),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('tool_key', sa.String(length=160), nullable=True),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver_role', sa.String(length=32), nullable=False),
    sa.Column('resolver_user_id', sa.String(length=40), nullable=True),
    sa.Column('resolution_rationale', sa.Text(), nullable=True),
    sa.Column('timeout_action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_trace_id'), ['trace_id'], unique=False)

    op.create_table('audit_checkpoints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_checkpoints_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_checkpoints_seq'), ['seq'], unique=False)

    op.create_table('audit_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('prev_digest', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_seq'), ['seq'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_entries_subject_id'), ['subject_id'], unique=False)

    op.create_table('baselines',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('suite_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselines_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_suite_id'), ['suite_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=24), nullable=False),
    sa.Column('scope_id', sa.String(length=120), nullable=False),
    sa.Column('window', sa.String(length=24), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('max_cost_usd', sa.Float(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_scope_id'), ['scope_id'], unique=False)

    op.create_table('control_statuses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('control_key', sa.String(length=32), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_statuses_control_key'), ['control_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_statuses_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_ctlstatus_key_time', ['control_key', 'computed_at'], unique=False)

    op.create_table('controls',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('pillar', sa.Integer(), nullable=False),
    sa.Column('implemented_by', sa.JSON(), nullable=False),
    sa.Column('evidence_sources', sa.JSON(), nullable=False),
    sa.Column('status_rule_json', sa.JSON(), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controls_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_controls_org_id'), ['org_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('span_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('identity_id', sa.String(length=40), nullable=True),
    sa.Column('surface', sa.String(length=24), nullable=False),
    sa.Column('tool_key', sa.String(length=160), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('rules_fired_json', sa.JSON(), nullable=False),
    sa.Column('policy_version_id', sa.String(length=40), nullable=True),
    sa.Column('policy_version_ids', sa.JSON(), nullable=False),
    sa.Column('detector_run_ids', sa.JSON(), nullable=False),
    sa.Column('taint_summary_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_decisions_agent_verdict', ['agent_id', 'verdict', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_verdict'), ['verdict'], unique=False)

    op.create_table('delegation_edges',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('parent_identity_id', sa.String(length=40), nullable=False),
    sa.Column('child_identity_id', sa.String(length=40), nullable=False),
    sa.Column('capability_diff_json', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delegation_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegation_edges_child_identity_id'), ['child_identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_edges_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_edges_parent_identity_id'), ['parent_identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_edges_trace_id'), ['trace_id'], unique=False)

    op.create_table('detection_findings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('detector_run_id', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('sample', sa.String(length=200), nullable=False),
    sa.Column('action_taken', sa.String(length=24), nullable=False),
    sa.Column('owasp_id', sa.String(length=24), nullable=True),
    sa.Column('atlas_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_findings_detector_run_id'), ['detector_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_findings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_findings_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_detfind_entity', ['entity_type', 'created_at'], unique=False)

    op.create_table('detector_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('span_id', sa.String(length=40), nullable=True),
    sa.Column('detector_key', sa.String(length=64), nullable=False),
    sa.Column('detector_version', sa.String(length=32), nullable=False),
    sa.Column('surface', sa.String(length=24), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detector_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detector_runs_detector_key'), ['detector_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_detector_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detector_runs_trace_id'), ['trace_id'], unique=False)

    op.create_table('drift_windows',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('scorer_key', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.Column('psi', sa.Float(), nullable=True),
    sa.Column('ks', sa.Float(), nullable=True),
    sa.Column('baseline_window_id', sa.String(length=40), nullable=True),
    sa.Column('drifted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_windows_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_windows_org_id'), ['org_id'], unique=False)

    op.create_table('eval_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('scorer_key', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', 'scorer_key', name='uq_eval_result')
    )
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_results_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_results_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_results_run_id'), ['run_id'], unique=False)

    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('suite_id', sa.String(length=40), nullable=False),
    sa.Column('target_json', sa.JSON(), nullable=False),
    sa.Column('scorer_keys', sa.JSON(), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('runner', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('code_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_runs_suite_id'), ['suite_id'], unique=False)

    op.create_table('eval_suites',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_suites_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_eval_suites_org_id'), ['org_id'], unique=False)

    op.create_table('evidence_packages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('chain_verification_json', sa.JSON(), nullable=False),
    sa.Column('code_version', sa.String(length=40), nullable=False),
    sa.Column('catalog_version', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_packages_org_id'), ['org_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('control_keys', sa.JSON(), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('suppressed_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_findings_triage', ['status', 'severity', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_type'), ['type'], unique=False)

    op.create_table('framework_mappings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('control_key', sa.String(length=32), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('framework_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_mappings_control_key'), ['control_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mappings_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mappings_org_id'), ['org_id'], unique=False)

    op.create_table('legal_holds',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('placed_by', sa.String(length=120), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_holds_org_id'), ['org_id'], unique=False)

    op.create_table('lineage_edges',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('src_type', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.String(length=120), nullable=False),
    sa.Column('dst_type', sa.String(length=32), nullable=False),
    sa.Column('dst_id', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('observed_count', sa.Integer(), nullable=False),
    sa.Column('declared', sa.Boolean(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_id', 'dst_id', 'relation', name='uq_lineage_edge')
    )
    with op.batch_alter_table('lineage_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_edges_dst_id'), ['dst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_edges_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_edges_src_id'), ['src_id'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('pinned_version', sa.String(length=64), nullable=True),
    sa.Column('trust_level', sa.String(length=24), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_org_id'), ['org_id'], unique=False)

    op.create_table('obligations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applies_when_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligations_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_org_id'), ['org_id'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_policies_org_id'), ['org_id'], unique=False)

    op.create_table('policy_bindings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('policy_version_id', sa.String(length=40), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_bindings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_bindings_policy_version_id'), ['policy_version_id'], unique=False)

    op.create_table('redteam_campaigns',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('runner', sa.String(length=24), nullable=False),
    sa.Column('probes', sa.JSON(), nullable=False),
    sa.Column('target_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redteam_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redteam_campaigns_org_id'), ['org_id'], unique=False)

    op.create_table('redteam_findings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('probe', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('owasp_id', sa.String(length=24), nullable=True),
    sa.Column('atlas_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redteam_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redteam_findings_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redteam_findings_org_id'), ['org_id'], unique=False)

    op.create_table('retention_policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('data_class', sa.String(length=64), nullable=False),
    sa.Column('retain_days', sa.Integer(), nullable=False),
    sa.Column('redact_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_class')
    )
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_policies_org_id'), ['org_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('eu_ai_act_class', sa.String(length=24), nullable=False),
    sa.Column('inherent_risk', sa.String(length=16), nullable=False),
    sa.Column('residual_risk', sa.String(length=16), nullable=False),
    sa.Column('mitigations_json', sa.JSON(), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('assessor', sa.String(length=120), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_org_id'), ['org_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=40), nullable=True),
    sa.Column('candidate_body', sa.Text(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('replayed_count', sa.Integer(), nullable=False),
    sa.Column('diff_json', sa.JSON(), nullable=False),
    sa.Column('run_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_org_id'), ['org_id'], unique=False)

    op.create_table('slos',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('scorer_key', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('window', sa.String(length=24), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('error_budget_remaining', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slos_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slos_org_id'), ['org_id'], unique=False)

    op.create_table('spans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=False),
    sa.Column('parent_span_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spans_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_spans_trace_time', ['trace_id', 'started_at'], unique=False)

    op.create_table('taint_tags',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trust', sa.String(length=16), nullable=False),
    sa.Column('propagated_from', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taint_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taint_tags_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taint_tags_trace_id'), ['trace_id'], unique=False)

    op.create_table('tools',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('impact', sa.String(length=24), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('mcp_server_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_tools_org_id'), ['org_id'], unique=False)

    op.create_table('traces',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('agent_slug', sa.String(length=120), nullable=True),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('token_usage_json', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traces_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_agent_slug'), ['agent_slug'], unique=False)
        batch_op.create_index('ix_traces_agent_time', ['agent_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_verdict'), ['verdict'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('agent_controls',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_state', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_controls_agent_id'), ['agent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_controls_org_id'), ['org_id'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('eval_cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('suite_id', sa.String(length=40), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('expected_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('split', sa.String(length=24), nullable=False),
    sa.Column('source_trace_id', sa.String(length=40), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['eval_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_cases_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_cases_suite_id'), ['suite_id'], unique=False)

    op.create_table('identities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('principal', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posture', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identities_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_principal'), ['principal'], unique=True)

    op.create_table('mcp_tool_snapshots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('mcp_server_id', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tools_json', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tool_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tool_snapshots_mcp_server_id'), ['mcp_server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_snapshots_org_id'), ['org_id'], unique=False)

    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('compiled_json', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_version')
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_versions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_versions_policy_id'), ['policy_id'], unique=False)

    op.create_table('capabilities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('identity_id', sa.String(length=40), nullable=False),
    sa.Column('tool_key', sa.String(length=160), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('max_taint', sa.String(length=24), nullable=False),
    sa.Column('granted_by', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capabilities_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capabilities_org_id'), ['org_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('identity_id', sa.String(length=40), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from_id', sa.String(length=40), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_org_id'))
        batch_op.drop_index(batch_op.f('ix_credentials_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_credentials_identity_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capabilities_org_id'))
        batch_op.drop_index(batch_op.f('ix_capabilities_identity_id'))

    op.drop_table('capabilities')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_versions_org_id'))

    op.drop_table('policy_versions')
    with op.batch_alter_table('mcp_tool_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tool_snapshots_org_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_snapshots_mcp_server_id'))

    op.drop_table('mcp_tool_snapshots')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_principal'))
        batch_op.drop_index(batch_op.f('ix_identities_org_id'))
        batch_op.drop_index(batch_op.f('ix_identities_agent_id'))

    op.drop_table('identities')
    with op.batch_alter_table('eval_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_cases_suite_id'))
        batch_op.drop_index(batch_op.f('ix_eval_cases_org_id'))

    op.drop_table('eval_cases')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_key_prefix'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('agent_controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_controls_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_controls_agent_id'))

    op.drop_table('agent_controls')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_verdict'))
        batch_op.drop_index(batch_op.f('ix_traces_session_id'))
        batch_op.drop_index(batch_op.f('ix_traces_org_id'))
        batch_op.drop_index('ix_traces_agent_time')
        batch_op.drop_index(batch_op.f('ix_traces_agent_slug'))
        batch_op.drop_index(batch_op.f('ix_traces_agent_id'))

    op.drop_table('traces')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_org_id'))
        batch_op.drop_index(batch_op.f('ix_tools_key'))

    op.drop_table('tools')
    with op.batch_alter_table('taint_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taint_tags_trace_id'))
        batch_op.drop_index(batch_op.f('ix_taint_tags_org_id'))

    op.drop_table('taint_tags')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index('ix_spans_trace_time')
        batch_op.drop_index(batch_op.f('ix_spans_trace_id'))
        batch_op.drop_index(batch_op.f('ix_spans_org_id'))

    op.drop_table('spans')
    with op.batch_alter_table('slos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slos_org_id'))
        batch_op.drop_index(batch_op.f('ix_slos_agent_id'))

    op.drop_table('slos')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_org_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_org_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_agent_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_policies_org_id'))

    op.drop_table('retention_policies')
    with op.batch_alter_table('redteam_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redteam_findings_org_id'))
        batch_op.drop_index(batch_op.f('ix_redteam_findings_campaign_id'))

    op.drop_table('redteam_findings')
    with op.batch_alter_table('redteam_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redteam_campaigns_org_id'))

    op.drop_table('redteam_campaigns')
    with op.batch_alter_table('policy_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_bindings_policy_version_id'))
        batch_op.drop_index(batch_op.f('ix_policy_bindings_org_id'))

    op.drop_table('policy_bindings')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_org_id'))
        batch_op.drop_index(batch_op.f('ix_policies_key'))

    op.drop_table('policies')
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligations_org_id'))
        batch_op.drop_index(batch_op.f('ix_obligations_framework'))

    op.drop_table('obligations')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_org_id'))

    op.drop_table('mcp_servers')
    with op.batch_alter_table('lineage_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_edges_src_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_edges_org_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_edges_dst_id'))

    op.drop_table('lineage_edges')
    with op.batch_alter_table('legal_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_holds_org_id'))

    op.drop_table('legal_holds')
    with op.batch_alter_table('framework_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_mappings_org_id'))
        batch_op.drop_index(batch_op.f('ix_framework_mappings_framework'))
        batch_op.drop_index(batch_op.f('ix_framework_mappings_control_key'))

    op.drop_table('framework_mappings')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_type'))
        batch_op.drop_index('ix_findings_triage')
        batch_op.drop_index(batch_op.f('ix_findings_subject_id'))
        batch_op.drop_index(batch_op.f('ix_findings_org_id'))

    op.drop_table('findings')
    with op.batch_alter_table('evidence_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_packages_org_id'))

    op.drop_table('evidence_packages')
    with op.batch_alter_table('eval_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_suites_org_id'))
        batch_op.drop_index(batch_op.f('ix_eval_suites_key'))

    op.drop_table('eval_suites')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_suite_id'))
        batch_op.drop_index(batch_op.f('ix_eval_runs_org_id'))

    op.drop_table('eval_runs')
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_eval_results_org_id'))
        batch_op.drop_index(batch_op.f('ix_eval_results_case_id'))

    op.drop_table('eval_results')
    with op.batch_alter_table('drift_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_windows_org_id'))
        batch_op.drop_index(batch_op.f('ix_drift_windows_agent_id'))

    op.drop_table('drift_windows')
    with op.batch_alter_table('detector_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detector_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_detector_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_detector_runs_detector_key'))

    op.drop_table('detector_runs')
    with op.batch_alter_table('detection_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_detfind_entity')
        batch_op.drop_index(batch_op.f('ix_detection_findings_trace_id'))
        batch_op.drop_index(batch_op.f('ix_detection_findings_org_id'))
        batch_op.drop_index(batch_op.f('ix_detection_findings_detector_run_id'))

    op.drop_table('detection_findings')
    with op.batch_alter_table('delegation_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegation_edges_trace_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_edges_parent_identity_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_edges_org_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_edges_child_identity_id'))

    op.drop_table('delegation_edges')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_verdict'))
        batch_op.drop_index(batch_op.f('ix_decisions_trace_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_org_id'))
        batch_op.drop_index('ix_decisions_agent_verdict')
        batch_op.drop_index(batch_op.f('ix_decisions_agent_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controls_org_id'))
        batch_op.drop_index(batch_op.f('ix_controls_key'))

    op.drop_table('controls')
    with op.batch_alter_table('control_statuses', schema=None) as batch_op:
        batch_op.drop_index('ix_ctlstatus_key_time')
        batch_op.drop_index(batch_op.f('ix_control_statuses_org_id'))
        batch_op.drop_index(batch_op.f('ix_control_statuses_control_key'))

    op.drop_table('control_statuses')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_scope_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_org_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_suite_id'))
        batch_op.drop_index(batch_op.f('ix_baselines_org_id'))

    op.drop_table('baselines')
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_subject_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_action'))

    op.drop_table('audit_entries')
    with op.batch_alter_table('audit_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_checkpoints_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_checkpoints_org_id'))

    op.drop_table('audit_checkpoints')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_trace_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_decision_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_agent_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_slug'))
        batch_op.drop_index(batch_op.f('ix_agents_org_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
