"""policy hierarchy and agent controls

Revision ID: b87fa49f9b09
Revises: 1549f3f1dbf8
Create Date: 2026-08-18 19:36:43.173471
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b87fa49f9b09'
down_revision: str | None = '1549f3f1dbf8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_bindings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('scope_id', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('compose', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_bindings', schema=None) as batch_op:
        batch_op.drop_column('compose')
        batch_op.drop_column('scope_id')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
